
version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: test
      DEBUG: "True"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - "5000:80"   # Web UI
      - "25:25"     # SMTP
      - "143:143"   
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: