[tool.black]
line-length = 79
target-version = ["py313"]
skip-string-normalization = true


[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 79
extend-ignore = [
    "E203",  # conflict with black
    "W503",  # line break before binary operator
]
exclude = [
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    "env",
    "build",
    "dist",
    settings.py,
]
