name: Django Project Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run tests
        run: docker compose exec backend sh -c "flake8 && pytest ."

